name: Release Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2

      - name: Add stable download ZIP
        run: cp .release/KekwSoundBoard-*.zip .release/KekwSoundBoard.zip

      - uses: softprops/action-gh-release@v2
        with:
          files: .release/KekwSoundBoard.zip
